# Generated by Django 4.1.2 on 2022-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="image_path",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
