# Generated by Django 4.1.2 on 2022-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_artwork_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="image_path",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
