# Generated by Django 4.1.2 on 2022-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_artwork_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="artist",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="image_path",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
